name: track_it
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl:
  equatable:
  flutter_secure_storage: ^9.2.2
  flutter_svg:
  go_router:
  get_it:
  fluttertoast: ^8.2.10
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  pinput: ^5.0.0
  lottie: ^3.2.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  hive_generator:
# flutter packages pub run build_runner build

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/lottie/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: ZkBlack
      fonts:
        - asset: assets/fonts/zk-regular.ttf
          weight: 400
        - asset: assets/fonts/zk-medium.ttf
          weight: 500
        - asset: assets/fonts/zk-bold.ttf
          weight: 800
        - asset: assets/fonts/zk-black.ttf
          weight: 900
