// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWPwoSKyElhciL-DLz_Dg1m-_zD1Qm0E',
    appId: '1:838682859343:android:363e5aea96bc81c11e973a',
    messagingSenderId: '838682859343',
    projectId: 'na-hive-pg',
    databaseURL: 'https://na-hive-pg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'na-hive-pg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGv4s-rTNdnCufYdF5UiaXnI7UrbQ0nzc',
    appId: '1:838682859343:ios:22a3d1fed16a5b231e973a',
    messagingSenderId: '838682859343',
    projectId: 'na-hive-pg',
    databaseURL: 'https://na-hive-pg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'na-hive-pg.firebasestorage.app',
    androidClientId: '838682859343-tcldkefgolofe0j75fhn3jlfj69gr5g6.apps.googleusercontent.com',
    iosClientId: '838682859343-2c1n8ergp6jvmurhfphpijjmivjrvtch.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackIt',
  );
}
